// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UseInfo.proto

package com.humanvoyage.pb;

public final class UseInfoPb {
  private UseInfoPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.humanvoyage.pb.UseInfoPb.GetUseInfoRq.ext);
    registry.add(com.humanvoyage.pb.UseInfoPb.GetUseInfoRs.ext);
  }
  public interface GetUseInfoRqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 sid = 1;
    /**
     * <code>optional int32 sid = 1;</code>
     *
     * <pre>
     *登录token，用作账号验证
     * </pre>
     */
    boolean hasSid();
    /**
     * <code>optional int32 sid = 1;</code>
     *
     * <pre>
     *登录token，用作账号验证
     * </pre>
     */
    int getSid();
  }
  /**
   * Protobuf type {@code GetUseInfoRq}
   *
   * <pre>
   * </pre>
   */
  public static final class GetUseInfoRq extends
      com.google.protobuf.GeneratedMessage
      implements GetUseInfoRqOrBuilder {
    // Use GetUseInfoRq.newBuilder() to construct.
    private GetUseInfoRq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetUseInfoRq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetUseInfoRq defaultInstance;
    public static GetUseInfoRq getDefaultInstance() {
      return defaultInstance;
    }

    public GetUseInfoRq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetUseInfoRq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sid_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.humanvoyage.pb.UseInfoPb.internal_static_GetUseInfoRq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.humanvoyage.pb.UseInfoPb.internal_static_GetUseInfoRq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.humanvoyage.pb.UseInfoPb.GetUseInfoRq.class, com.humanvoyage.pb.UseInfoPb.GetUseInfoRq.Builder.class);
    }

    public static com.google.protobuf.Parser<GetUseInfoRq> PARSER =
        new com.google.protobuf.AbstractParser<GetUseInfoRq>() {
      public GetUseInfoRq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetUseInfoRq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetUseInfoRq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 sid = 1;
    public static final int SID_FIELD_NUMBER = 1;
    private int sid_;
    /**
     * <code>optional int32 sid = 1;</code>
     *
     * <pre>
     *登录token，用作账号验证
     * </pre>
     */
    public boolean hasSid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 sid = 1;</code>
     *
     * <pre>
     *登录token，用作账号验证
     * </pre>
     */
    public int getSid() {
      return sid_;
    }

    private void initFields() {
      sid_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, sid_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.humanvoyage.pb.UseInfoPb.GetUseInfoRq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.humanvoyage.pb.UseInfoPb.GetUseInfoRq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.humanvoyage.pb.UseInfoPb.GetUseInfoRq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.humanvoyage.pb.UseInfoPb.GetUseInfoRq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.humanvoyage.pb.UseInfoPb.GetUseInfoRq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.humanvoyage.pb.UseInfoPb.GetUseInfoRq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.humanvoyage.pb.UseInfoPb.GetUseInfoRq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.humanvoyage.pb.UseInfoPb.GetUseInfoRq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.humanvoyage.pb.UseInfoPb.GetUseInfoRq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.humanvoyage.pb.UseInfoPb.GetUseInfoRq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.humanvoyage.pb.UseInfoPb.GetUseInfoRq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetUseInfoRq}
     *
     * <pre>
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.humanvoyage.pb.UseInfoPb.GetUseInfoRqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.humanvoyage.pb.UseInfoPb.internal_static_GetUseInfoRq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.humanvoyage.pb.UseInfoPb.internal_static_GetUseInfoRq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.humanvoyage.pb.UseInfoPb.GetUseInfoRq.class, com.humanvoyage.pb.UseInfoPb.GetUseInfoRq.Builder.class);
      }

      // Construct using com.humanvoyage.pb.UseInfoPb.GetUseInfoRq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.humanvoyage.pb.UseInfoPb.internal_static_GetUseInfoRq_descriptor;
      }

      public com.humanvoyage.pb.UseInfoPb.GetUseInfoRq getDefaultInstanceForType() {
        return com.humanvoyage.pb.UseInfoPb.GetUseInfoRq.getDefaultInstance();
      }

      public com.humanvoyage.pb.UseInfoPb.GetUseInfoRq build() {
        com.humanvoyage.pb.UseInfoPb.GetUseInfoRq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.humanvoyage.pb.UseInfoPb.GetUseInfoRq buildPartial() {
        com.humanvoyage.pb.UseInfoPb.GetUseInfoRq result = new com.humanvoyage.pb.UseInfoPb.GetUseInfoRq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sid_ = sid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.humanvoyage.pb.UseInfoPb.GetUseInfoRq) {
          return mergeFrom((com.humanvoyage.pb.UseInfoPb.GetUseInfoRq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.humanvoyage.pb.UseInfoPb.GetUseInfoRq other) {
        if (other == com.humanvoyage.pb.UseInfoPb.GetUseInfoRq.getDefaultInstance()) return this;
        if (other.hasSid()) {
          setSid(other.getSid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.humanvoyage.pb.UseInfoPb.GetUseInfoRq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.humanvoyage.pb.UseInfoPb.GetUseInfoRq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 sid = 1;
      private int sid_ ;
      /**
       * <code>optional int32 sid = 1;</code>
       *
       * <pre>
       *登录token，用作账号验证
       * </pre>
       */
      public boolean hasSid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 sid = 1;</code>
       *
       * <pre>
       *登录token，用作账号验证
       * </pre>
       */
      public int getSid() {
        return sid_;
      }
      /**
       * <code>optional int32 sid = 1;</code>
       *
       * <pre>
       *登录token，用作账号验证
       * </pre>
       */
      public Builder setSid(int value) {
        bitField0_ |= 0x00000001;
        sid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sid = 1;</code>
       *
       * <pre>
       *登录token，用作账号验证
       * </pre>
       */
      public Builder clearSid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sid_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GetUseInfoRq)
    }

    static {
      defaultInstance = new GetUseInfoRq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GetUseInfoRq)
    public static final int EXT_FIELD_NUMBER = 101;
    /**
     * <code>extend .Base { ... }</code>
     *
     * <pre>
     *登录token，用作账号验证
     * </pre>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.humanvoyage.pb.BasePb.Base,
        com.humanvoyage.pb.UseInfoPb.GetUseInfoRq> ext = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.humanvoyage.pb.UseInfoPb.GetUseInfoRq.getDefaultInstance(),
          0,
          com.humanvoyage.pb.UseInfoPb.GetUseInfoRq.class,
          com.humanvoyage.pb.UseInfoPb.GetUseInfoRq.getDefaultInstance());
  }

  public interface GetUseInfoRsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 keyId = 1;
    /**
     * <code>optional int32 keyId = 1;</code>
     */
    boolean hasKeyId();
    /**
     * <code>optional int32 keyId = 1;</code>
     */
    int getKeyId();
  }
  /**
   * Protobuf type {@code GetUseInfoRs}
   */
  public static final class GetUseInfoRs extends
      com.google.protobuf.GeneratedMessage
      implements GetUseInfoRsOrBuilder {
    // Use GetUseInfoRs.newBuilder() to construct.
    private GetUseInfoRs(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetUseInfoRs(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetUseInfoRs defaultInstance;
    public static GetUseInfoRs getDefaultInstance() {
      return defaultInstance;
    }

    public GetUseInfoRs getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetUseInfoRs(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              keyId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.humanvoyage.pb.UseInfoPb.internal_static_GetUseInfoRs_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.humanvoyage.pb.UseInfoPb.internal_static_GetUseInfoRs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.humanvoyage.pb.UseInfoPb.GetUseInfoRs.class, com.humanvoyage.pb.UseInfoPb.GetUseInfoRs.Builder.class);
    }

    public static com.google.protobuf.Parser<GetUseInfoRs> PARSER =
        new com.google.protobuf.AbstractParser<GetUseInfoRs>() {
      public GetUseInfoRs parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetUseInfoRs(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetUseInfoRs> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 keyId = 1;
    public static final int KEYID_FIELD_NUMBER = 1;
    private int keyId_;
    /**
     * <code>optional int32 keyId = 1;</code>
     */
    public boolean hasKeyId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 keyId = 1;</code>
     */
    public int getKeyId() {
      return keyId_;
    }

    private void initFields() {
      keyId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, keyId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, keyId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.humanvoyage.pb.UseInfoPb.GetUseInfoRs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.humanvoyage.pb.UseInfoPb.GetUseInfoRs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.humanvoyage.pb.UseInfoPb.GetUseInfoRs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.humanvoyage.pb.UseInfoPb.GetUseInfoRs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.humanvoyage.pb.UseInfoPb.GetUseInfoRs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.humanvoyage.pb.UseInfoPb.GetUseInfoRs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.humanvoyage.pb.UseInfoPb.GetUseInfoRs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.humanvoyage.pb.UseInfoPb.GetUseInfoRs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.humanvoyage.pb.UseInfoPb.GetUseInfoRs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.humanvoyage.pb.UseInfoPb.GetUseInfoRs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.humanvoyage.pb.UseInfoPb.GetUseInfoRs prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetUseInfoRs}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.humanvoyage.pb.UseInfoPb.GetUseInfoRsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.humanvoyage.pb.UseInfoPb.internal_static_GetUseInfoRs_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.humanvoyage.pb.UseInfoPb.internal_static_GetUseInfoRs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.humanvoyage.pb.UseInfoPb.GetUseInfoRs.class, com.humanvoyage.pb.UseInfoPb.GetUseInfoRs.Builder.class);
      }

      // Construct using com.humanvoyage.pb.UseInfoPb.GetUseInfoRs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        keyId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.humanvoyage.pb.UseInfoPb.internal_static_GetUseInfoRs_descriptor;
      }

      public com.humanvoyage.pb.UseInfoPb.GetUseInfoRs getDefaultInstanceForType() {
        return com.humanvoyage.pb.UseInfoPb.GetUseInfoRs.getDefaultInstance();
      }

      public com.humanvoyage.pb.UseInfoPb.GetUseInfoRs build() {
        com.humanvoyage.pb.UseInfoPb.GetUseInfoRs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.humanvoyage.pb.UseInfoPb.GetUseInfoRs buildPartial() {
        com.humanvoyage.pb.UseInfoPb.GetUseInfoRs result = new com.humanvoyage.pb.UseInfoPb.GetUseInfoRs(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.keyId_ = keyId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.humanvoyage.pb.UseInfoPb.GetUseInfoRs) {
          return mergeFrom((com.humanvoyage.pb.UseInfoPb.GetUseInfoRs)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.humanvoyage.pb.UseInfoPb.GetUseInfoRs other) {
        if (other == com.humanvoyage.pb.UseInfoPb.GetUseInfoRs.getDefaultInstance()) return this;
        if (other.hasKeyId()) {
          setKeyId(other.getKeyId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.humanvoyage.pb.UseInfoPb.GetUseInfoRs parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.humanvoyage.pb.UseInfoPb.GetUseInfoRs) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 keyId = 1;
      private int keyId_ ;
      /**
       * <code>optional int32 keyId = 1;</code>
       */
      public boolean hasKeyId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 keyId = 1;</code>
       */
      public int getKeyId() {
        return keyId_;
      }
      /**
       * <code>optional int32 keyId = 1;</code>
       */
      public Builder setKeyId(int value) {
        bitField0_ |= 0x00000001;
        keyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 keyId = 1;</code>
       */
      public Builder clearKeyId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        keyId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GetUseInfoRs)
    }

    static {
      defaultInstance = new GetUseInfoRs(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GetUseInfoRs)
    public static final int EXT_FIELD_NUMBER = 102;
    /**
     * <code>extend .Base { ... }</code>
     *
     * <pre>
     *登录token，用作账号验证
     * </pre>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.humanvoyage.pb.BasePb.Base,
        com.humanvoyage.pb.UseInfoPb.GetUseInfoRs> ext = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.humanvoyage.pb.UseInfoPb.GetUseInfoRs.getDefaultInstance(),
          0,
          com.humanvoyage.pb.UseInfoPb.GetUseInfoRs.class,
          com.humanvoyage.pb.UseInfoPb.GetUseInfoRs.getDefaultInstance());
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUseInfoRq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetUseInfoRq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUseInfoRs_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetUseInfoRs_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rUseInfo.proto\032\nBase.proto\">\n\014GetUseInf" +
      "oRq\022\013\n\003sid\030\001 \001(\0052!\n\003ext\022\005.Base\030e \001(\0132\r.G" +
      "etUseInfoRq\"@\n\014GetUseInfoRs\022\r\n\005keyId\030\001 \001" +
      "(\0052!\n\003ext\022\005.Base\030f \001(\0132\r.GetUseInfoRsB\037\n" +
      "\022com.humanvoyage.pbB\tUseInfoPb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_GetUseInfoRq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_GetUseInfoRq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GetUseInfoRq_descriptor,
              new java.lang.String[] { "Sid", });
          internal_static_GetUseInfoRs_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_GetUseInfoRs_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GetUseInfoRs_descriptor,
              new java.lang.String[] { "KeyId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.humanvoyage.pb.BasePb.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
